### ISSUE TITLE
Timetable error

### ISSUE THREAD

**Issue by NGJ14** [NGJ14/thengakola.com#9]
Card empty and status free for 3 people though class not completed

Arsha
Georgy
Naveen 

And for Neha:
Next class timing: 18:00 - 17:30

**Comment by ro-jc** [comment]
> Card empty and status free for 3 people though class not completed

Any idea when it started?

**Comment by NGJ14** [comment]
> > Card empty and status free for 3 people though class not completed
> 
> Any idea when it started?

It was fine in the morning
It was like this when i checked half n hour back

**Comment by ro-jc** [comment]
fixed in commit b5690aa
